// Date: 14/04/2013 14:33:20
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelGrinder extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape2;
    ModelRenderer Shape2;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
  
  public ModelGrinder()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
      Shape1.setRotationPoint(-8F, 23F, -8F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 71, 0);
      Shape2.addBox(0F, 0F, 0F, 1, 2, 12);
      Shape2.setRotationPoint(5F, 21F, -6F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 71, 0);
      Shape2.addBox(0F, 0F, 0F, 1, 2, 12);
      Shape2.setRotationPoint(-6F, 21F, -6F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 71, 0);
      Shape2.addBox(0F, 0F, 0F, 12, 2, 1);
      Shape2.setRotationPoint(-6F, 21F, 5F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 71, 0);
      Shape2.addBox(0F, 0F, 0F, 12, 2, 1);
      Shape2.setRotationPoint(-6F, 21F, -6F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 21);
      Shape3.addBox(0F, 0F, 0F, 2, 6, 2);
      Shape3.setRotationPoint(6F, 17F, -8F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 63, 21);
      Shape3.addBox(0F, 0F, 0F, 2, 6, 2);
      Shape3.setRotationPoint(6F, 17F, 6F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 98, 12);
      Shape3.addBox(0F, 0F, 0F, 2, 6, 2);
      Shape3.setRotationPoint(-8F, 17F, 6F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 99, 0);
      Shape3.addBox(0F, 0F, 0F, 2, 6, 2);
      Shape3.setRotationPoint(-8F, 17F, -8F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 34);
      Shape1.addBox(0F, 0F, 0F, 14, 1, 14);
      Shape1.setRotationPoint(-7F, 17F, -7F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 75, 31);
      Shape2.addBox(0F, 0F, 0F, 10, 2, 10);
      Shape2.setRotationPoint(-5F, 18F, -5F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
